Lidar_front_end:
   lidar_type: 1   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 1
   using_raw_point: 1
   point_step: 1
   min_intensity: 20.0
   min_dist: 0.1
   lidar_imu_rotm:
      # LiDAR is mounted rotated by 90 deg
      #[1, 0, 0,
      # 0, 0, 1,
      # 0, -1, 0]
      [ 0.999982746499287,   -0.00177553621213092, -0.00559947987785364,
        0.00558619409134593, -0.00727614642368604,  0.999957925179252,
       -0.00181644036584728, -0.999971950070678,   -0.00726633444330636]
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 0            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 0        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 0            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 100  # The point step of append point to global map. [default = 4]

r3live_vio:
   # This is the projection intrinsics used for the rest of the calculations
   camera_intrinsic:
      # Fisheye1 intrinsics
      # [ 284.867889404297, 0.0, 423.566009521484, 
      #   0.0, 285.978393554688, 396.071685791016,
      #   0.0, 0.0, 1.0]
      [285.013488769531, 0.0, 431.468200683594,
       0.0, 286.051391601562, 402.149291992188,
       0.0, 0.0, 1.0]
   # This is the real camera intrinsics used for computing the undistort map for fisheye
   camera_intrinsic_real:
      [285.013488769531, 0.0, 431.468200683594,
       0.0, 286.051391601562, 402.149291992188,
       0.0, 0.0, 1.0]
   # Hacked in r3live_vio.cpp to be fisheye instead of normal pinhole
   camera_dist_coeffs: [-0.00379493203945458, 0.0425821505486965, -0.0402233116328716, 0.0073482571169734, 0]  #k1, k2, p1, p2, k3
   # Camera->IMU value derived from T265 factory calibration.
   camera_ext_R:
         [ 0.00272182077459558,  -0.000150018042693227,   0.999996284586227,
          -0.999996209806378,   0.000414414086947048,   0.00272188057107007,
          -0.000414820959711679, -0.999999902877816,  -0.000148888985539575]
         #[0, 0, 1,
         # -1, 0, 0,
         # 0, -1, 0]
   #camera_ext_t: [-0.013776, 0.0347174, -0.0972432] 
   camera_ext_t: [ 0, 0, 0 ]
   
r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 2           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   
   filter_size_surf: 0.30
   filter_size_surf_z: 0.30
   filter_size_map: 0.30
   publish_feature_map: 1
